<?php

namespace Julien\Bundle\ArtistBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExponentRepository extends EntityRepository
{
}
